status = [
	"ci/hydra:flake:staging:checks.aarch64-linux.pre-commit-check",
	"ci/hydra:flake:staging:checks.x86_64-linux.pre-commit-check",
	"ci/hydra:flake:staging:devShells.aarch64-linux.default",
	"ci/hydra:flake:staging:devShells.x86_64-linux.default",
	"ci/hydra:flake:staging:formatter.aarch64-linux",
	"ci/hydra:flake:staging:formatter.x86_64-linux",
	"ci/hydra:flake:staging:homeConfigurations.aarch64-linux.seth",
	"ci/hydra:flake:staging:homeConfigurations.x86_64-linux.seth",
	"ci/hydra:flake:staging:hosts.atlas",
	"ci/hydra:flake:staging:hosts.glados",
	"ci/hydra:flake:staging:hosts.glados-wsl",
	"ci/hydra:flake:staging:hosts.p-body"
]

delete_merged_branches = true
