{
  imports = [
    ./acme.nix
    ./budgie.nix
    ./catppuccin.nix
    ./comin.nix
    ./forgejo.nix
    ./gnome.nix
    ./home-manager.nix
    ./kanidm.nix
    ./lanzaboote.nix
    ./nginx.nix
    ./niri.nix
    ./nvidia.nix
    ./pipewire.nix
    ./plasma.nix
    ./resolved.nix
    ./tailscale.nix
    ./zram.nix
  ];
}
