{
  imports = [
    ./acme.nix
    ./agenix.nix
    ./budgie.nix
    ./catppuccin.nix
    ./comin.nix
    ./dix.nix
    ./fonts.nix
    ./forgejo.nix
    ./gnome.nix
    ./hedgedoc.nix
    ./home-manager.nix
    ./kanidm.nix
    ./lanzaboote.nix
    ./lix.nix
    ./miniflux.nix
    ./nginx.nix
    ./niri.nix
    ./nix.nix
    ./nvidia.nix
    ./pipewire.nix
    ./plasma.nix
    ./resolved.nix
    ./security.nix
    ./tailscale.nix
    ./users.nix
    ./wsl.nix
    ./xserver.nix
    ./zram.nix
  ];
}
