{
  imports = [
    ./acme.nix
    ./agenix.nix
    ./budgie.nix
    ./catppuccin.nix
    ./forgejo.nix
    ./gnome.nix
    ./grafana.nix
    ./hedgedoc.nix
    ./home-manager.nix
    ./journal-upload.nix
    ./kanidm.nix
    ./lanzaboote.nix
    ./miniflux.nix
    ./nginx.nix
    ./niri.nix
    ./node-exporter.nix
    ./nvidia.nix
    ./pipewire.nix
    ./plasma.nix
    ./resolved.nix
    ./tailscale.nix
    ./wsl.nix
    ./zram.nix
  ];
}
