name: "update flake inputs"
description: "wrapper around DeterminateSystems/update-flake-lock"
inputs:
  commit-msg:
    required: true
  github-token:
    description: "github read token for increasing rate limits"
    required: true
    default: ""
  inputs:
    description: "flake inputs to update"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: install nix
      uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ inputs.github-token }}

    - name: run update-flake-lock
      uses: DeterminateSystems/update-flake-lock@v19
      id: update
      with:
        commit-msg: ${{ inputs.commit-msg }}
        inputs: ${{ inputs.inputs }}
        nix-options: "--accept-flake-config"
        pr-body: |
          Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.
        pr-title: ${{ inputs.commit-msg }}
        token: ${{ inputs.github-token }}

    - name: auto-merge pull request
      shell: bash
      run: gh pr merge --auto --rebase "$PR_ID"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_ID: ${{ steps.update.outputs.pull-request-number }}
