name: "update flake inputs"
description: "wrapper around DeterminateSystems/update-flake-lock"
inputs:
  update-token:
    description: "github write token for creating prs"
    required: true
  github-token:
    description: "github read token for avoid rate limits"
    required: false
    default: ""
  inputs:
    description: "flake inputs to update"
    required: false
    default: ""
  commit-msg:
    required: true
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ inputs.github-token }}

    - uses: DeterminateSystems/update-flake-lock@v19
      with:
        commit-msg: ${{ inputs.commit-msg }}
        pr-title: ${{ inputs.commit-msg }}
        pr-body: |
          Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

          bors r+
        nix-options: "--accept-flake-config"
        token: ${{ inputs.update-token }}
