name: "update flake inputs"
description: "wrapper around DeterminateSystems/update-flake-lock"
inputs:
  update-token:
    description: "github write token for creating prs"
    required: true
  github-token:
    description: "github read token for avoid rate limits"
    required: false
    default: ""
  inputs:
    description: "flake inputs to update"
    required: false
    default: ""
  commit-msg:
    required: true
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ inputs.github-token }}

    - uses: DeterminateSystems/update-flake-lock@v19
      id: update
      with:
        commit-msg: ${{ inputs.commit-msg }}
        pr-title: ${{ inputs.commit-msg }}
        nix-options: "--accept-flake-config"
        token: ${{ inputs.update-token }}

    - name: auto-merge pull request
      run: gh pr merge --auto --squash "$PR_ID"
      env:
        GITHUB_TOKEN: ${{ inputs.update-token }}
        PR_ID: ${{ steps.update.outputs.pull-request-number }}
