name: Install Nix

description: "Install an implementation of Nix"

inputs:
  variant:
    description: "Nix implementation to install. Either Nix, Lix, or Dix"
    required: true
    default: "Nix"

runs:
  using: composite
  steps:
    - name: Install Nix
      if: ${{ inputs.variant == 'Nix' }}
      uses: cachix/install-nix-action@v31

    - name: Install Lix
      if: ${{ inputs.variant == 'Lix' }}
      uses: samueldr/lix-gha-installer-action@v1

    - name: Install Determinate Nix
      if: ${{ inputs.variant == 'Dix' }}
      uses: DeterminateSystems/determinate-nix-action@v3
