name: Deploy infrastructure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  nixos:
    needs: ci

    name: Deploy NixOS systems
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Setup local Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:gha

      - name: Copy known_hosts
        run: |
          set -eux

          [ ! -d ~/.ssh ] && mkdir -p ~/.ssh
          cp .known_hosts ~/.ssh/known_hosts

      - name: Run deploy
        run: |
          nix run --inputs-from . nixpkgs#deploy-rs -- -s

  opentofu:
    needs: nixos

    name: Apply OpenTofu plan
    runs-on: ubuntu-latest

    concurrency:
      group: tofu
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Setup local Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Setup OpenTofu cache
        uses: terraform-cache/terraform-cache@v1

      - name: Authenticate with TF Cloud
        run: |
          dir="$HOME/.terraform.d"
          [ ! -d "$dir" ] && mkdir -p "$dir"

          cat > "$dir"/credentials.tfrc.json << EOF
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${{ secrets.TF_API_TOKEN }}"
              }
            }
          }
          EOF

      - name: Generate configuration
        run: nix run .#gen-tf

      - name: Init workspace
        run: |
          nix run --inputs-from . \
            nixpkgs#opentofu -- init

      - name: Validate plan
        run: |
          nix run --inputs-from . \
            nixpkgs#opentofu -- validate

      - name: Apply
        run: |
          nix run --inputs-from . \
            nixpkgs#opentofu -- apply -auto-approve
