name: update nixpkgs inputs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-lock:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install nix
        uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: update inputs
        run: nix flake lock --update-input nixpkgs --update-input nixpkgsUnstable --update-input openwrt-imagebuilder

      - name: add and commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: update nixpkgs inputs"
  check:
    uses: ./.github/workflows/check.yml
