name: update all inputs

on:
  schedule:
    # run every saturday
    - cron: "0 0 * * 6"
  workflow_dispatch:

permissions: read-all

jobs:
  update-lock:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install nix
        uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: getchoo

      - name: update all inputs
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          inputs: nixpkgs nixpkgsUnstable
          commit-msg: "chore: update all inputs"
          pr-title: "chore: update all inputs"
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

            ```
            ${{ env.GIT_COMMIT_MESSAGE }}
            ```

            bors r+
          nix-options: "--accept-flake-config"
          token: ${{ secrets.FLAKE_UPDATE }}
