name: update all flake inputs

on:
  schedule:
    # run every saturday
    - cron: "0 0 * * 6"
  workflow_dispatch:

jobs:
  update:
    uses: ./.github/workflows/update-lock.yaml
    with:
      commit-msg: "flake: update all inputs"
    secrets:
      token: ${{ secrets.MERGE_TOKEN }}
