name: Update nixpkgs flake inputs

on:
  schedule:
    # run every day besides saturday at 0:00 utc
    - cron: "0 0 * * 0,1,2,3,4,5"
  workflow_dispatch:

jobs:
  update:
    uses: ./.github/workflows/update-lock.yaml
    with:
      commit-message: "flake: update nixpkgs"
      flake-inputs: "nixpkgs nixpkgs-stable"
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
