name: update nixpkgs flake inputs

on:
  schedule:
    # run daily at 0:00 utc
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    uses: ./.github/workflows/update-lock.yaml
    with:
      commit-msg: "flake: update nixpkgs"
      inputs: "nixpkgs nixpkgs-stable"
    secrets:
      token: ${{ secrets.MERGE_TOKEN }}
