name: Update all flake inputs

on:
  schedule:
    # run every saturday at 0:00 utc
    - cron: "0 0 * * 6"
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write

    uses: ./.github/workflows/update-lock.yaml
    with:
      commit-msg: "flake: update all inputs"
