name: update nixpkgs inputs

on:
  schedule:
    # run daily at 0:00 utc
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-nixpkgs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/flake-update
        with:
          commit-msg: "flake: update nixpkgs inputs"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          inputs: nixpkgs nixpkgs-stable
          update-token: ${{ secrets.FLAKE_UPDATE }}
