name: Update nixpkgs flake inputs

on:
  schedule:
    # run every day besides saturday at 0:00 utc
    - cron: "0 0 * * 0,1,2,3,4,5"
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write

    uses: ./.github/workflows/update-lock.yaml
    with:
      commit-msg: "flake: update nixpkgs"
      inputs: "nixpkgs nixpkgs-stable"
